import {NextResponse} from 'next/server';
import {adminClient,encrypt,decrypt,requireAdmin,hasSupabase} from '../../../../lib/server';
import {initLocal,localProfiles,localAddProfile,localUpdateProfile,localHideProfile,localRestoreProfile} from '../../../../lib/store';
const durations=[10,20,30,45,60];
function validate(b){if(!b.name?.trim())throw new Error('নাম দিন।');const age=Number(b.age);if(!Number.isInteger(age)||age<18)throw new Error('বয়স ১৮ বা তার বেশি হতে হবে।');if(!b.realImo?.trim())throw new Error('আসল Imo নম্বর দিন।');if(!b.photo?.trim())throw new Error('ছবি upload/select করুন।');for(const d of durations){const v=Number(b['price'+d]);if(!Number.isFinite(v)||v<0)throw new Error(`${d} মিনিটের price সঠিক দিন।`)}return {...b,age,prices:Object.fromEntries(durations.map(d=>[d,Number(b['price'+d])]))}}
function publicShape(p){return {...p,realImo:undefined,real_imo_encrypted:undefined}}
function adminShape(p){return {...p,realImo:p.realImo??decrypt(p.real_imo_encrypted)}}
async function dbOrLocal(){if(hasSupabase())return {type:'supabase',db:adminClient()};return {type:'local',db:await initLocal()}}
export async function GET(req){if(!requireAdmin(req))return NextResponse.json({error:'Unauthorized'},{status:401});try{const c=await dbOrLocal();if(c.type==='local')return NextResponse.json({profiles:(await localProfiles()).map(adminShape),mode:'local'});const {data,error}=await c.db.from('profiles').select('*').order('created_at',{ascending:false});if(error)throw error;return NextResponse.json({profiles:(data||[]).map(adminShape),mode:'supabase'})}catch(e){return NextResponse.json({error:e.message||'Could not load profiles'},{status:500})}}
export async function POST(req){if(!requireAdmin(req))return NextResponse.json({error:'Unauthorized'},{status:401});try{const b=validate(await req.json());const p={name:b.name.trim(),age:b.age,price:b.prices[10],price_10:b.prices[10],price_20:b.prices[20],price_30:b.prices[30],price_45:b.prices[45],price_60:b.prices[60],realImo:b.realImo.trim(),photo:b.photo.trim(),bio:b.bio||'',languages:Array.isArray(b.languages)?b.languages:(b.languages||'Bengali, English').split(',').map(x=>x.trim()).filter(Boolean),gallery:b.gallery||[b.photo.trim()],online:Boolean(b.online),rating:5,reviews:0,active:b.active!==false};const c=await dbOrLocal();let row;if(c.type==='local')row=await localAddProfile(p);else{const {data,error}=await c.db.from('profiles').insert({...p,real_imo_encrypted:encrypt(p.realImo)}).select('*').single();if(error)throw error;row=adminShape(data)}return NextResponse.json({profile:adminShape(row),mode:c.type},{status:201})}catch(e){return NextResponse.json({error:e.message||'Profile could not be added'},{status:400})}}
export async function PUT(req){if(!requireAdmin(req))return NextResponse.json({error:'Unauthorized'},{status:401});try{const b=validate(await req.json());if(!b.id)throw new Error('Profile id missing');const patch={name:b.name.trim(),age:b.age,price:b.prices[10],price_10:b.prices[10],price_20:b.prices[20],price_30:b.prices[30],price_45:b.prices[45],price_60:b.prices[60],realImo:b.realImo.trim(),photo:b.photo.trim(),bio:b.bio||'',languages:Array.isArray(b.languages)?b.languages:(b.languages||'').split(',').map(x=>x.trim()).filter(Boolean),gallery:b.gallery||[b.photo.trim()],online:Boolean(b.online),active:b.active!==false};const c=await dbOrLocal();let row;if(c.type==='local')row=await localUpdateProfile(b.id,patch);else{const {data,error}=await c.db.from('profiles').update({...patch,real_imo_encrypted:encrypt(patch.realImo)}).eq('id',b.id).select('*').single();if(error)throw error;row=adminShape(data)}return NextResponse.json({profile:adminShape(row),mode:c.type})}catch(e){return NextResponse.json({error:e.message||'Profile could not be updated'},{status:400})}}
export async function DELETE(req){if(!requireAdmin(req))return NextResponse.json({error:'Unauthorized'},{status:401});try{const {id,restore}=await req.json();const c=await dbOrLocal();if(c.type==='local'){const p=restore?await localRestoreProfile(id):await localHideProfile(id);return NextResponse.json({profile:adminShape(p)})}const {data,error}=await c.db.from('profiles').update({active:Boolean(restore)}).eq('id',id).select('*').single();if(error)throw error;return NextResponse.json({profile:adminShape(data)})}catch(e){return NextResponse.json({error:e.message||'Profile status update failed'},{status:400})}}
