import crypto from 'crypto';
import {NextResponse} from 'next/server';
import {adminClient,hasSupabase} from '../../../../lib/server';
import {localAddPaymentAndMatch,localPaymentDeviceHeartbeat} from '../../../../lib/store';
function deviceAuthorized(req){const expected=(process.env.PAYMENT_DEVICE_TOKEN||'').trim(),got=(req.headers.get('x-payment-device-token')||'').trim();if(!expected||!got||expected.length!==got.length)return false;return crypto.timingSafeEqual(Buffer.from(got),Buffer.from(expected))}
function normPhone(v){return String(v||'').replace(/\D/g,'').replace(/^88/,'').replace(/^0?/,'0')}
function validProvider(v){return ['bkash','nagad'].includes(String(v||'').trim().toLowerCase())}
function allowedSender(provider,sender){const raw=(provider==='bkash'?process.env.BKASH_SMS_SENDERS:process.env.NAGAD_SMS_SENDERS)||'';const list=raw.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return !list.length || list.includes(String(sender||'').trim().toLowerCase())}
export async function POST(req){try{if(!deviceAuthorized(req))return NextResponse.json({error:'Unauthorized payment device'},{status:401});const b=await req.json(),deviceId=String(b.deviceId||'').trim().slice(0,100),appVersion=String(b.appVersion||'').trim().slice(0,40),deviceModel=String(b.deviceModel||'').trim().slice(0,120),provider=String(b.provider||'').trim().toLowerCase(),source=normPhone(b.paymentSource||b.payment_source),amount=Number(b.amount),smsSender=String(b.smsSender||b.sms_sender||'').trim(),receivedAt=new Date(b.receivedAt||b.received_at||Date.now()),raw=typeof b.sms==='string'?b.sms.trim():'';if(!/^[A-Za-z0-9._:-]{8,100}$/.test(deviceId)||!validProvider(provider)||!allowedSender(provider,smsSender)||!/^(01\d{9})$/.test(source)||!Number.isFinite(amount)||amount<=0||amount>1000000||!raw||raw.length>4000||Number.isNaN(receivedAt.getTime()))return NextResponse.json({error:'Invalid payment SMS data'},{status:400});if(!hasSupabase()) await localPaymentDeviceHeartbeat({device_key:deviceId,app_version:appVersion,device_model:deviceModel,last_sms_at:receivedAt.toISOString(),last_upload_at:new Date().toISOString(),last_result:'received'});
const smsHash=crypto.createHash('sha256').update(`${provider}|${source}|${amount}|${receivedAt.toISOString()}|${raw}`).digest('hex'),event={provider,payment_source:source,amount,received_at:receivedAt.toISOString(),sms_hash:smsHash,sms_text:raw,sms_sender:smsSender};if(!hasSupabase()){try{const result=await localAddPaymentAndMatch(event);return NextResponse.json({ok:true,matched:result.matched,bookingId:result.booking?.id||null})}catch(e){if(e.code==='DUPLICATE_SMS')return NextResponse.json({ok:true,matched:false,duplicate:true});throw e}}await adminClient().from('payment_devices').upsert({device_key:deviceId,app_version:appVersion,device_model:deviceModel,last_seen_at:new Date().toISOString(),last_sms_at:receivedAt.toISOString(),last_upload_at:new Date().toISOString(),last_result:'received'},{onConflict:'device_key'});
const ins=await adminClient().from('payment_events').insert(event).select('id').single();if(ins.error){if(ins.error.code==='23505')return NextResponse.json({ok:true,matched:false,duplicate:true});throw ins.error}const receivedMs=receivedAt.getTime(),min=new Date(receivedMs-15*60*1000).toISOString(),max=new Date(receivedMs+2*60*1000).toISOString();const {data:pending,error:pe}=await adminClient().from('bookings').select('id,code,status').eq('status','pending').eq('provider',provider).eq('payment_source',source).eq('price',amount).gte('created_at',min).lte('created_at',max).order('created_at',{ascending:true}).limit(1).maybeSingle();if(pe)throw pe;if(!pending)return NextResponse.json({ok:true,matched:false});const upd=await adminClient().from('bookings').update({status:'approved',payment_event_id:ins.data.id}).eq('id',pending.id).eq('status','pending').select('id,code,status').maybeSingle();if(upd.error)throw upd.error;if(!upd.data)return NextResponse.json({ok:true,matched:false,race:true});await adminClient().from('payment_events').update({used:true,booking_id:upd.data.id}).eq('id',ins.data.id);return NextResponse.json({ok:true,matched:true,bookingId:upd.data.id,code:upd.data.code})}catch(e){return NextResponse.json({error:e.message||'Payment SMS processing failed'},{status:500})}}
